### ISSUE TITLE
Move transform schemas out of asdf-standard

### ISSUE THREAD

**Issue by perrygreenfield** [asdf-format/asdf-standard#241]
There is a larger discussion of this on the [wiki](https://github.com/asdf-format/asdf-standard/wiki/2.0.0-roadmap), but the main reasons are to:

- Make the basic standard more stable since more and more transforms are being added leading to frequent asdf-standard updates
- Reduce the implementer's burden of supporting the standard in languages and domains that do not need what transforms supply.

**Comment by embray** [comment]
I think I always felt this didn't belong in the core standard.  Good idea.

**Comment by embray** [comment]
I obviously haven't kept up very recently with the state of ASDF, but where do schemas get installed to currently and how are they searched by the asdf library for Python?  Are they always shipped as Python package data?

It might make sense if there was a standard search path for schemas that's independent of the implementation (i.e. not tied to Python in any way).  But the standard could make a requirement on implementations for what the default search path is and/or how it can be modified.  The library implementation would also handle schema downloads, rather than tying that to a packaging system.  I'm mentally making an analogy here to how [nltk](https://www.nltk.org/data.html) handles downloading of external data.  This could happen either automatically or require manual intervention, perhaps depending on a setting.

Maybe I'm completely off track though.  Like I said, I'm out of the loop...

**Comment by eslavich** [comment]
> where do schemas get installed to currently and how are they searched by the asdf library for Python? Are they always shipped as Python package data?

Yes, that's the current state of things.  The Python library's extension API is to provide schema and tag URI prefixes that are claimed by the extension, and also a template that is used to convert a matching URI into a URL where the schema content can be accessed.  This system is a little inflexible and has proven to be a source of confusion for extension authors, so we are looking for a better way.

Lately I've been thinking we should change the extension API to something more like this:

```
def schema_uris():
  # return a list of specific URIs claimed by the extension (as opposed to a prefix)

def read_schema(uri):
  # return the schema content and not a URL
```

This would give the extensions more flexibility on how they fetch the list of schemas and their content -- could be `importlib.resources`, a string constant in the Python code, a web service that provides a dynamic list of available URIs, etc.
