### ISSUE TITLE
Time schema validates arbitrary ndarray objects that converters cannot interpret as time

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf-standard#352]
Neither the converter in astropy or asdf-astropy supports the reference to the ndarray object, I vote for removing the reference:
https://github.com/asdf-format/asdf-standard/blob/ecdf2648b75fc99053fa33a5ff06cab1561af5eb/resources/schemas/stsci.edu/asdf/time/time-1.2.0.yaml#L197
For example, the following is valid yaml if the ndarray reference is kept:
```yaml
!time/time-1.1.0
  data: [1, 2, 3]
```
So this validates during reading, but fails during conversion to astropy.Time.

**Comment by WilliamJamieson** [comment]
I think the original goal of this was to support formulations that look like:
```yaml
!time/time-1.1.0
  !core/ndarray-1.0.0
    data: ['2000-01-01 00:00:00.000', '2000-01-01 00:00:00.001', '2000-01-01 00:00:00.002']
```

However, one cannot have two tags like this and be valid, so really it has to be of the form:
```yaml
!time/time-1.1.0 ['2000-01-01 00:00:00.000', '2000-01-01 00:00:00.001', '2000-01-01 00:00:00.002']
```

or

```yaml
!time/time-1.1.0
  data: ['2000-01-01 00:00:00.000', '2000-01-01 00:00:00.001', '2000-01-01 00:00:00.002']
```

to be valid yaml.

The first is covered by: https://github.com/asdf-format/asdf-standard/blob/ecdf2648b75fc99053fa33a5ff06cab1561af5eb/resources/schemas/stsci.edu/asdf/time/time-1.1.0.yaml#L125

The question is do we want to support using the term `data` in addition to `value` to hold the actual time values/data?  Currently the converter only supports:
```yaml
!time/time-1.1.0
  value: ['2000-01-01 00:00:00.000', '2000-01-01 00:00:00.001', '2000-01-01 00:00:00.002']
```

In this case we do have to be careful in the schema for `data`(replicating `value`) because `astropy.time.Time` only supports a limited input for its value (covered by what is in `value`).

**Comment by WilliamJamieson** [comment]
After going through the above analysis, I agree that we should drop this sort of array "support" from the schema.
